### ISSUE TITLE
The car drives too erratically 

### ISSUE THREAD

**Issue by Joey-Banaszak** [Joey-Banaszak/cs386-a1#5]
On my drive the other day the cars lane sensor system seemed to be too sensitive and would swerve to correct too often, would prefer a much smoother correction process.

**Comment by gmv53** [comment]
Maybe we shouldn’t have modeled it after Izaac’s driving style 💯

**Comment by imolina97** [comment]
Could you potentially describe in what situations the system seemed to correct too drastically?

**Comment by imolina97** [comment]
This is likely related to #6 , I think something with the system's detection is causing both issues
